"""
Daily Report Static Site Builder
Converts Markdown files to HTML pages for GitHub Pages.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
import re
import shutil

import markdown

from config import get_config

TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title} - Daily Report</title>
  <link rel="stylesheet" href="{base_path}style.css">
</head>
<body>
  <nav class="navbar">
    <div class="container">
      <a href="{base_path}index.html" class="logo">📰 Daily Report</a>
      <div class="nav-links">
        <a href="{base_path}index.html">首页</a>
        <a href="{base_path}archive.html">近期归档</a>
      </div>
    </div>
  </nav>

  <main class="container">
    <article class="content">
      <header class="article-header">
        <h1>{title}</h1>
        <time datetime="{date}">{date_display}</time>
      </header>
      <div class="markdown-body">
{content}
      </div>
    </article>
  </main>

  <footer class="footer">
    <div class="container">
      <p>Generated by Daily Report · {build_time}</p>
    </div>
  </footer>
</body>
</html>
"""

INDEX_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Daily Report - AI 新闻日报</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <nav class="navbar">
    <div class="container">
      <a href="index.html" class="logo">📰 Daily Report</a>
      <div class="nav-links">
        <a href="index.html" class="active">首页</a>
        <a href="archive.html">近期归档</a>
      </div>
    </div>
  </nav>

  <main class="container">
    <section class="hero">
      <h1>AI 新闻日报</h1>
      <p>自动抓取、智能总结、每日更新</p>
    </section>

    <section class="latest">
      <h2>📌 最新日报</h2>
      {latest_card}
    </section>

    <section class="recent">
      <h2>📅 近期日报</h2>
      <div class="card-grid">
{recent_cards}
      </div>
    </section>
  </main>

  <footer class="footer">
    <div class="container">
      <p>Generated by Daily Report · {build_time}</p>
    </div>
  </footer>
</body>
</html>
"""

ARCHIVE_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>近期归档 - Daily Report</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <nav class="navbar">
    <div class="container">
      <a href="index.html" class="logo">📰 Daily Report</a>
      <div class="nav-links">
        <a href="index.html">首页</a>
        <a href="archive.html" class="active">近期归档</a>
      </div>
    </div>
  </nav>

  <main class="container">
    <h1>📚 近期日报归档</h1>
    <p>站点当前只展示仓库保留窗口内的日报；更早历史请到 GitHub Release 归档资产查看。</p>
    <div class="archive-list">
{archive_items}
    </div>
  </main>

  <footer class="footer">
    <div class="container">
      <p>Generated by Daily Report · {build_time}</p>
    </div>
  </footer>
</body>
</html>
"""


def resolve_paths(
    source_dir: Path | None = None,
    output_dir: Path | None = None,
    assets_dir: Path | None = None,
) -> tuple[Path, Path, Path]:
    """Resolve site build paths from arguments or runtime config."""
    cfg = get_config()
    return (
        source_dir or Path(cfg.content_dir),
        output_dir or Path(cfg.site_dir),
        assets_dir or Path("assets"),
    )


def parse_frontmatter(content: str) -> tuple[dict[str, str], str]:
    """Parse YAML frontmatter from markdown content."""
    meta = {"title": "Untitled", "date": ""}
    body = content

    if content.startswith("---"):
        parts = content.split("---", 2)
        if len(parts) >= 3:
            for line in parts[1].strip().split("\n"):
                if ":" in line:
                    key, value = line.split(":", 1)
                    meta[key.strip()] = value.strip()
            body = parts[2]

    return meta, body


def convert_ol_to_paragraphs(html: str) -> str:
    """Convert ordered lists to numbered paragraphs for easier copy/paste."""

    def replace_ol(match: re.Match[str]) -> str:
        ol_content = match.group(1)
        items = re.findall(r"<li>\s*<p>(.+?)</p>\s*</li>", ol_content, re.DOTALL)
        paragraphs = [
            f"<p>{index}. {item.strip()}</p>" for index, item in enumerate(items, 1)
        ]
        return "\n".join(paragraphs)

    return re.sub(r"<ol>(.+?)</ol>", replace_ol, html, flags=re.DOTALL)


def build_article(md_path: Path, base_path: str = "") -> dict[str, str]:
    """Build a single article HTML from a markdown file."""
    content = md_path.read_text(encoding="utf-8")
    meta, body = parse_frontmatter(content)

    html_content = markdown.markdown(
        body,
        extensions=["tables", "fenced_code", "codehilite", "toc"],
    )
    html_content = convert_ol_to_paragraphs(html_content)

    date = meta.get("date") or md_path.stem
    title = meta.get("title") or f"日报 {date}"

    try:
        date_obj = datetime.strptime(date, "%Y-%m-%d")
        date_display = date_obj.strftime("%Y年%m月%d日")
    except ValueError:
        date_display = date

    html = TEMPLATE.format(
        title=title,
        date=date,
        date_display=date_display,
        content=html_content,
        base_path=base_path,
        build_time=datetime.now().strftime("%Y-%m-%d %H:%M"),
    )

    return {
        "filename": f"{md_path.stem}.html",
        "title": title,
        "date": date,
        "date_display": date_display,
        "html": html,
    }


def build_card(article: dict[str, str], featured: bool = False) -> str:
    """Generate a card HTML for article listing."""
    card_class = "card featured" if featured else "card"
    return f"""
      <a href="{article["filename"]}" class="{card_class}">
        <h3>{article["title"]}</h3>
        <time>{article["date_display"]}</time>
      </a>"""


def prepare_output_dir(output_dir: Path) -> None:
    """Reset the dedicated build output directory before each build."""
    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)


def build_site(
    source_dir: Path | None = None,
    output_dir: Path | None = None,
    assets_dir: Path | None = None,
) -> list[dict[str, str]]:
    """Build the entire static site."""
    source_dir, output_dir, assets_dir = resolve_paths(
        source_dir, output_dir, assets_dir
    )

    print("🚀 Building Daily Report site...")
    source_dir.mkdir(parents=True, exist_ok=True)
    prepare_output_dir(output_dir)

    if assets_dir.exists():
        for asset in assets_dir.glob("*"):
            if asset.is_file():
                shutil.copy(asset, output_dir / asset.name)
        print(f"📦 Copied assets from {assets_dir}")

    md_files = sorted(source_dir.glob("*.md"), reverse=True)
    if not md_files:
        print(f"⚠️  No markdown files found in {source_dir}/")
        print("   Building an empty site with retention-window guidance.")

    articles: list[dict[str, str]] = []
    for md_path in md_files:
        article = build_article(md_path)
        articles.append(article)

        output_path = output_dir / article["filename"]
        output_path.write_text(article["html"], encoding="utf-8")
        print(f"✅ Built: {article['filename']}")

    build_time = datetime.now().strftime("%Y-%m-%d %H:%M")
    latest_card = (
        build_card(articles[0], featured=True)
        if articles
        else """
      <div class="card featured">
        <h3>暂无日报</h3>
        <p>当前仓库内还没有可构建的 Markdown 内容。</p>
      </div>"""
    )
    recent_cards = (
        "\n".join(build_card(article) for article in articles[1:6])
        if len(articles) > 1
        else "      <p>当前没有更多近期日报；更早历史请查看 GitHub Release 归档资产。</p>"
    )

    index_html = INDEX_TEMPLATE.format(
        latest_card=latest_card,
        recent_cards=recent_cards,
        build_time=build_time,
    )
    (output_dir / "index.html").write_text(index_html, encoding="utf-8")
    print("✅ Built: index.html")

    archive_items = (
        "\n".join(
            f'      <a href="{article["filename"]}" class="archive-item">'
            f'<span class="date">{article["date"]}</span>'
            f'<span class="title">{article["title"]}</span></a>'
            for article in articles
        )
        if articles
        else "      <p>当前仓库保留窗口内暂无日报内容。</p>"
    )
    archive_html = ARCHIVE_TEMPLATE.format(
        archive_items=archive_items,
        build_time=build_time,
    )
    (output_dir / "archive.html").write_text(archive_html, encoding="utf-8")
    print("✅ Built: archive.html")

    print(f"\n🎉 Site built successfully! Output: {output_dir.absolute()}")
    print(f"   Total articles: {len(articles)}")
    return articles


if __name__ == "__main__":
    build_site()
