"""
Daily Report Static Site Builder
Converts Markdown files to beautiful HTML pages for GitHub Pages
"""
import markdown
from pathlib import Path
from datetime import datetime
import shutil
import json

# Configuration
SOURCE_DIR = Path("content")      # Markdown source files
OUTPUT_DIR = Path("docs")         # GitHub Pages serves from /docs
ASSETS_DIR = Path("assets")       # CSS/JS assets

TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title} - Daily Report</title>
  <link rel="stylesheet" href="{base_path}style.css">
</head>
<body>
  <nav class="navbar">
    <div class="container">
      <a href="{base_path}index.html" class="logo">📰 Daily Report</a>
      <div class="nav-links">
        <a href="{base_path}index.html">首页</a>
        <a href="{base_path}archive.html">归档</a>
      </div>
    </div>
  </nav>
  
  <main class="container">
    <article class="content">
      <header class="article-header">
        <h1>{title}</h1>
        <time datetime="{date}">{date_display}</time>
      </header>
      <div class="markdown-body">
{content}
      </div>
    </article>
  </main>
  
  <footer class="footer">
    <div class="container">
      <p>Generated by Daily Report · {build_time}</p>
    </div>
  </footer>
</body>
</html>
"""

INDEX_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Daily Report - AI 新闻日报</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <nav class="navbar">
    <div class="container">
      <a href="index.html" class="logo">📰 Daily Report</a>
      <div class="nav-links">
        <a href="index.html" class="active">首页</a>
        <a href="archive.html">归档</a>
      </div>
    </div>
  </nav>
  
  <main class="container">
    <section class="hero">
      <h1>AI 新闻日报</h1>
      <p>自动抓取、智能总结、每日更新</p>
    </section>
    
    <section class="latest">
      <h2>📌 最新日报</h2>
      {latest_card}
    </section>
    
    <section class="recent">
      <h2>📅 近期日报</h2>
      <div class="card-grid">
{recent_cards}
      </div>
    </section>
  </main>
  
  <footer class="footer">
    <div class="container">
      <p>Generated by Daily Report · {build_time}</p>
    </div>
  </footer>
</body>
</html>
"""

ARCHIVE_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>归档 - Daily Report</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <nav class="navbar">
    <div class="container">
      <a href="index.html" class="logo">📰 Daily Report</a>
      <div class="nav-links">
        <a href="index.html">首页</a>
        <a href="archive.html" class="active">归档</a>
      </div>
    </div>
  </nav>
  
  <main class="container">
    <h1>📚 日报归档</h1>
    <div class="archive-list">
{archive_items}
    </div>
  </main>
  
  <footer class="footer">
    <div class="container">
      <p>Generated by Daily Report · {build_time}</p>
    </div>
  </footer>
</body>
</html>
"""


def parse_frontmatter(content: str) -> tuple[dict, str]:
    """Parse YAML frontmatter from markdown content"""
    meta = {"title": "Untitled", "date": ""}
    body = content
    
    if content.startswith("---"):
        parts = content.split("---", 2)
        if len(parts) >= 3:
            for line in parts[1].strip().split("\n"):
                if ":" in line:
                    key, value = line.split(":", 1)
                    meta[key.strip()] = value.strip()
            body = parts[2]
    
    return meta, body


def build_article(md_path: Path, base_path: str = "") -> dict:
    """Build a single article HTML from markdown file"""
    content = md_path.read_text(encoding="utf-8")
    meta, body = parse_frontmatter(content)
    
    # Convert markdown to HTML
    html_content = markdown.markdown(
        body,
        extensions=["tables", "fenced_code", "codehilite", "toc"]
    )
    
    # Extract date from filename if not in frontmatter
    date = meta.get("date") or md_path.stem
    title = meta.get("title") or f"日报 {date}"
    
    # Format date for display
    try:
        date_obj = datetime.strptime(date, "%Y-%m-%d")
        date_display = date_obj.strftime("%Y年%m月%d日")
    except ValueError:
        date_display = date
    
    # Generate HTML
    html = TEMPLATE.format(
        title=title,
        date=date,
        date_display=date_display,
        content=html_content,
        base_path=base_path,
        build_time=datetime.now().strftime("%Y-%m-%d %H:%M")
    )
    
    return {
        "filename": md_path.stem + ".html",
        "title": title,
        "date": date,
        "date_display": date_display,
        "html": html
    }


def build_card(article: dict, featured: bool = False) -> str:
    """Generate a card HTML for article listing"""
    card_class = "card featured" if featured else "card"
    return f"""
      <a href="{article['filename']}" class="{card_class}">
        <h3>{article['title']}</h3>
        <time>{article['date_display']}</time>
      </a>"""


def build_site():
    """Build the entire static site"""
    print("🚀 Building Daily Report site...")
    
    # Ensure directories exist
    OUTPUT_DIR.mkdir(exist_ok=True)
    SOURCE_DIR.mkdir(exist_ok=True)
    
    # Copy assets
    if ASSETS_DIR.exists():
        for asset in ASSETS_DIR.glob("*"):
            shutil.copy(asset, OUTPUT_DIR / asset.name)
        print(f"📦 Copied assets from {ASSETS_DIR}")
    
    # Find all markdown files
    md_files = sorted(SOURCE_DIR.glob("*.md"), reverse=True)
    
    if not md_files:
        print("⚠️  No markdown files found in content/")
        print("   Creating sample content...")
        create_sample_content()
        md_files = sorted(SOURCE_DIR.glob("*.md"), reverse=True)
    
    # Build articles
    articles = []
    for md_path in md_files:
        article = build_article(md_path)
        articles.append(article)
        
        # Write article HTML
        output_path = OUTPUT_DIR / article["filename"]
        output_path.write_text(article["html"], encoding="utf-8")
        print(f"✅ Built: {article['filename']}")
    
    # Build index page
    build_time = datetime.now().strftime("%Y-%m-%d %H:%M")
    
    latest_card = build_card(articles[0], featured=True) if articles else ""
    recent_cards = "\n".join(build_card(a) for a in articles[1:6]) if len(articles) > 1 else ""
    
    index_html = INDEX_TEMPLATE.format(
        latest_card=latest_card,
        recent_cards=recent_cards,
        build_time=build_time
    )
    (OUTPUT_DIR / "index.html").write_text(index_html, encoding="utf-8")
    print("✅ Built: index.html")
    
    # Build archive page
    archive_items = "\n".join(
        f'      <a href="{a["filename"]}" class="archive-item">'
        f'<span class="date">{a["date"]}</span>'
        f'<span class="title">{a["title"]}</span></a>'
        for a in articles
    )
    archive_html = ARCHIVE_TEMPLATE.format(
        archive_items=archive_items,
        build_time=build_time
    )
    (OUTPUT_DIR / "archive.html").write_text(archive_html, encoding="utf-8")
    print("✅ Built: archive.html")
    
    print(f"\n🎉 Site built successfully! Output: {OUTPUT_DIR.absolute()}")
    print(f"   Total articles: {len(articles)}")
    return articles


def create_sample_content():
    """Create sample markdown files for testing"""
    SOURCE_DIR.mkdir(exist_ok=True)
    
    sample1 = """---
title: AI 新闻日报 2026-01-19
date: 2026-01-19
---

## 🔥 今日热点

### OpenAI 发布 GPT-5 预览版
OpenAI 宣布开放 GPT-5 模型的有限预览，新模型在推理能力上有显著提升。

### Google DeepMind 推出 Gemini 2.0
继 Gemini 1.5 之后，DeepMind 发布了新一代多模态模型...

## 📰 行业动态

- **Anthropic** 获得新一轮融资
- **Meta** 开源新的 LLaMA 3.5 模型
- **Microsoft** 与 OpenAI 深化合作

## 💡 技术趋势

1. AI Agent 正在成为主流
2. 多模态能力持续进化
3. 推理效率大幅提升
"""
    
    sample2 = """---
title: AI 新闻日报 2026-01-18
date: 2026-01-18
---

## 🔥 今日热点

### Claude 3.5 Sonnet 性能提升
Anthropic 更新了 Claude 3.5 Sonnet，编程能力显著增强。

## 📰 行业动态

- 多家科技公司加大 AI 投入
- 开源模型生态持续繁荣
"""
    
    (SOURCE_DIR / "2026-01-19.md").write_text(sample1, encoding="utf-8")
    (SOURCE_DIR / "2026-01-18.md").write_text(sample2, encoding="utf-8")
    print("📝 Created sample content files")


if __name__ == "__main__":
    build_site()
